# Generated by Django 4.2.21 on 2025-06-11 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_checked', models.CharField(default='2', max_length=10)),
                ('extra', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField()),
                ('word_count', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('style', models.CharField(default='2', max_length=10)),
                ('is_selected', models.CharField(default='2', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('voice', models.CharField(blank=True, max_length=100)),
                ('url', models.TextField(blank=True)),
                ('local_url', models.CharField(blank=True, max_length=255)),
                ('word_id', models.CharField(blank=True, max_length=50)),
                ('error_num', models.CharField(blank=True, max_length=20)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='corpus.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='LessonTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('product_type', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField(blank=True)),
                ('check_url', models.TextField(blank=True)),
                ('is_selected', models.SmallIntegerField(default=0)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='LessonTest', to='corpus.unit')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='corpus.unit'),
        ),
    ]
