# Generated by Django 4.2.21 on 2025-06-09 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('style', models.CharField(default='2', max_length=10)),
                ('is_selected', models.CharField(default='2', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TestDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('unit_id', models.IntegerField(blank=True, null=True)),
                ('product_type', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField(blank=True)),
                ('check_url', models.TextField(blank=True)),
                ('lesson_id', models.IntegerField(blank=True, null=True)),
                ('is_selected', models.SmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('voice', models.CharField(blank=True, max_length=100)),
                ('url', models.TextField(blank=True)),
                ('local_url', models.CharField(blank=True, max_length=255)),
                ('word_id', models.CharField(blank=True, max_length=50)),
                ('error_num', models.CharField(blank=True, max_length=20)),
                ('lesson_id', models.IntegerField(blank=True, null=True)),
                ('test_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='corpus.testdetail')),
            ],
        ),
        migrations.CreateModel(
            name='TestPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_checked', models.CharField(default='2', max_length=10)),
                ('extra', models.CharField(blank=True, max_length=100)),
                ('url', models.URLField()),
                ('word_count', models.CharField(max_length=50)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='list', to='corpus.book')),
            ],
        ),
        migrations.AddField(
            model_name='testdetail',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='corpus.testpaper'),
        ),
    ]
