# Generated by Django 4.2.21 on 2025-06-09 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TestPaper',
            new_name='Unit',
        ),
    ]
