# Generated by Django 4.2.21 on 2025-06-11 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_rename_unit_lesson_a'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='a',
            new_name='book',
        ),
    ]
