# Generated by Django 4.2.21 on 2025-06-09 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0002_rename_testpaper_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='corpus.book'),
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(blank=True, max_length=255)),
                ('count', models.IntegerField(default=0)),
                ('unit_id', models.IntegerField(blank=True, null=True)),
                ('product_type', models.IntegerField(blank=True, null=True)),
                ('url', models.TextField(blank=True)),
                ('check_url', models.TextField(blank=True)),
                ('lesson_id', models.IntegerField(blank=True, null=True)),
                ('is_selected', models.SmallIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='corpus.unit')),
            ],
        ),
        migrations.AlterField(
            model_name='word',
            name='test_detail',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='words', to='corpus.lesson'),
        ),
        migrations.DeleteModel(
            name='TestDetail',
        ),
    ]
