# Generated by Django 4.2.21 on 2025-06-11 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0003_rename_a_lesson_book'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='book',
            new_name='unit',
        ),
    ]
