# Generated by Django 4.2.21 on 2025-06-11 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0005_lesson_error_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='more',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lesson',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, '未练习'), (2, '已练习')], default=1),
        ),
    ]
