# Generated by Django 4.2.21 on 2025-06-11 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0006_lesson_more_lesson_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='unit',
            name='intro',
            field=models.CharField(default='', max_length=100),
        ),
    ]
