# Generated by Django 4.2.21 on 2025-06-11 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0007_rename_name_unit_title_unit_intro'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='is_wrong',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '正确'), (2, '错误')], null=True),
        ),
        migrations.AddField(
            model_name='word',
            name='wrong_num',
            field=models.IntegerField(default=0),
        ),
    ]
