# Generated by Django 4.2.21 on 2025-06-11 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0008_word_is_wrong_word_wrong_num'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LessonTest',
        ),
    ]
