# Generated by Django 4.2.21 on 2025-06-13 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0010_remove_lesson_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='error_count',
            field=models.IntegerField(max_length=50),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='word_count',
            field=models.IntegerField(max_length=50),
        ),
    ]
