# Generated by Django 4.2.21 on 2025-06-19 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0011_alter_lesson_error_count_alter_lesson_word_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='word',
            name='word_id',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='error_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='word_count',
            field=models.IntegerField(),
        ),
    ]
