# Generated by Django 4.2.21 on 2025-06-19 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corpus', '0012_remove_word_word_id_alter_lesson_error_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='error_text',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
